#!/usr/bin/env bash
# wkong: manually set the user info in env first

set -ex

if [ -z "$@" ]; then
  COMMAND=(zsh)
else
  COMMAND=("$@")
fi

sudo -H -u "#${CI_BUILD_UID}" --preserve-env \
  PATH="${PATH}" \
  LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
  PYTHONPATH="${PYTHONPATH}" \
  ${COMMAND[@]}
